##################################################################################################
#  Es PersistentVolume
##################################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/es-data-dev"
---
##################################################################################################
#  ES PersistentVolumeClaim
##################################################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data-pvc-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
##################################################################################################
#  ES Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: es-service-dev
spec:
  selector:
    app: es-cluster-dev
  ports:
    - name: tcp
      port: 9200
      protocol: TCP
      nodePort: 30002
  type: NodePort
---
##################################################################################################
#  ES Ingress
##################################################################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: es-ingress-dev
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: es-service-dev
                port:
                  number: 9200
---
##################################################################################################
#  ES Service Transport
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster-dev
spec:
  clusterIP: None
  selector:
    app: es-cluster-dev
  ports:
    - name: transport
      port: 9300
---
##################################################################################################
#  ES ConfigMap
##################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config-dev
data:
  elasticsearch.yml: |
    cluster.name: sos-elastic-cluster-dev
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch-cluster-dev
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m
---
##################################################################################################
#  ES StatefulSet
##################################################################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esnode-dev
  labels:
    app: es-cluster-dev
spec:
  serviceName: elasticsearch
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: es-cluster-dev
  template:
    metadata:
      labels:
        app: es-cluster-dev
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
        - name: file-permissions
          image: busybox
          command: ['chmod','-R', '777', '/usr/share/elasticsearch/']
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
          securityContext:
            privileged: true
            runAsUser: 1000
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: es-config-dev
                  key: ES_JAVA_OPTS
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: es-config-dev
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data-pvc-dev